import { useEffect, useState } from 'react'
import { identityApi } from '../application/identity-api'
import Notification from '../../shared/components/notification'

const initial={nombres:'',apellidos:'',correo:'',password:'',rol:'VENDEDOR'}
function UsersPage(){
  const[users,setUsers]=useState([]);const[form,setForm]=useState(initial);const[open,setOpen]=useState(false);const[notice,setNotice]=useState({message:'',type:'success'})
  const load=async()=>{try{setUsers((await identityApi.listUsers()).data)}catch(error){setNotice({message:error.response?.data?.message||'No se pudieron cargar los usuarios.',type:'error'})}}
  useEffect(()=>{identityApi.listUsers().then(response=>setUsers(response.data)).catch(error=>setNotice({message:error.response?.data?.message||'No se pudieron cargar los usuarios.',type:'error'}))},[])
  const create=async event=>{event.preventDefault();try{await identityApi.createUser(form);setForm(initial);setOpen(false);setNotice({message:'Empleado creado.',type:'success'});load()}catch(error){setNotice({message:error.response?.data?.message||'No se pudo crear el empleado.',type:'error'})}}
  const updateState=async(user,estado)=>{try{await identityApi.updateStatus(user.id,estado);setNotice({message:`Usuario ${estado}.`,type:'success'});load()}catch(error){setNotice({message:error.response?.data?.message||'No se pudo actualizar.',type:'error'})}}
  return <section><Notification {...notice}/><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold text-gray-900">Gestión de empleados</h1><p className="mt-1 text-sm text-gray-500">Roles, bloqueo administrativo y acceso 2FA.</p></div><button onClick={()=>setOpen(!open)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">{open?'Cancelar':'+ Nuevo empleado'}</button></div>{open&&<form onSubmit={create} className="mb-6 grid gap-4 rounded-lg bg-white p-6 shadow-md md:grid-cols-3">{['nombres','apellidos','correo','password'].map(name=><input key={name} className="rounded-lg border border-gray-300 px-4 py-3" name={name} type={name==='password'?'password':name==='correo'?'email':'text'} placeholder={name==='password'?'contraseña':name} minLength={name==='password'?8:2} required value={form[name]} onChange={event=>setForm({...form,[name]:event.target.value})}/>)}<select className="rounded-lg border border-gray-300 px-4 py-3" value={form.rol} onChange={event=>setForm({...form,rol:event.target.value})}><option>VENDEDOR</option><option>ADMIN</option><option>AUDITOR</option></select><button className="rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white">Guardar empleado</button></form>}<div className="overflow-hidden rounded-lg bg-white shadow-md"><table className="min-w-full"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['Empleado','Correo','Rol','2FA','Estado','Acciones'].map(header=><th key={header} className="px-5 py-3 text-left">{header}</th>)}</tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-gray-100"><td className="px-5 py-4 font-semibold">{user.nombres} {user.apellidos}</td><td className="px-5 py-4 text-sm">{user.correo}</td><td className="px-5 py-4 text-sm">{user.rol_nombre}</td><td className="px-5 py-4 text-sm">{user.two_factor_enabled?'Activo':'No'}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${user.estado==='activo'?'bg-emerald-100 text-emerald-800':user.estado==='bloqueado'?'bg-red-100 text-red-800':'bg-gray-100 text-gray-700'}`}>{user.estado}</span></td><td className="space-x-2 px-5 py-4"><button onClick={()=>updateState(user,user.estado==='activo'?'inactivo':'activo')} className="rounded-lg border px-3 py-2 text-xs font-semibold">{user.estado==='activo'?'Desactivar':'Activar'}</button><button onClick={()=>updateState(user,'bloqueado')} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Bloquear</button></td></tr>)}</tbody></table></div></section>
}
export default UsersPage
