import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { analyticsApi } from '../application/analytics-api'
import { productApi } from '../../product-catalog/application/product-api'
import { useSession } from '../../identity-access/application/session-store'

const iso = date => date.toISOString().slice(0,10)
const initialDates = () => { const end=new Date(); const start=new Date(); start.setDate(end.getDate()-29); return {fechaInicio:iso(start),fechaFin:iso(end)} }
const money = value => `S/ ${Number(value||0).toFixed(2)}`

function AnalyticsDashboardPage(){
  const { plan }=useSession(); const [preset,setPreset]=useState('30'); const [filters,setFilters]=useState({...initialDates(),categoria:'',sku:''}); const [products,setProducts]=useState([]); const [report,setReport]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const categories=useMemo(()=>[...new Set(products.map(product=>product.categoria).filter(Boolean))].sort(),[products])
  useEffect(()=>{productApi.list().then(response=>setProducts(response.data||[])).catch(()=>{})},[])
  const load=async(nextFilters=filters)=>{setLoading(true);setError('');try{setReport((await analyticsApi.consolidated(nextFilters)).data)}catch(requestError){setError(requestError.response?.data?.message||'No se pudo generar el reporte analítico.')}finally{setLoading(false)}}
  useEffect(()=>{if(!plan?.dashboardAnalitico)return;let active=true;const dates=initialDates();analyticsApi.consolidated(dates).then(response=>{if(active)setReport(response.data)}).catch(requestError=>{if(active)setError(requestError.response?.data?.message||'No se pudo generar el reporte analítico.')});return()=>{active=false}},[plan])
  const changePreset=value=>{setPreset(value);if(value==='custom')return;const end=new Date();const start=new Date();if(value==='7')start.setDate(end.getDate()-6);else if(value==='month')start.setDate(1);else start.setDate(end.getDate()-29);const next={...filters,fechaInicio:iso(start),fechaFin:iso(end)};setFilters(next);load(next)}
  if(!plan?.dashboardAnalitico)return <section className="rounded-lg border border-amber-200 bg-amber-50 p-8"><p className="text-xs font-bold uppercase tracking-widest text-amber-700">Acceso restringido</p><h1 className="mt-3 text-2xl font-bold text-gray-900">Dashboard analítico</h1><p className="mt-2 text-gray-600">Esta capacidad está disponible exclusivamente en el plan Corporativo.</p></section>
  const indicators=report?.indicadores||{}
  return <section><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">Inteligencia de negocios</p><h1 className="mt-2 text-3xl font-bold text-gray-900">Dashboard analítico</h1><p className="mt-2 text-sm text-gray-500">Ventas, rotación de productos y variaciones netas de inventario.</p></div>
    <form onSubmit={event=>{event.preventDefault();load()}} className="mt-7 rounded-lg border border-gray-200 bg-white p-5 shadow-md"><div className="grid gap-4 lg:grid-cols-6"><label className="text-xs font-bold uppercase text-gray-500">Periodo<select className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-800" value={preset} onChange={event=>changePreset(event.target.value)}><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="month">Este mes</option><option value="custom">Personalizado</option></select></label><label className="text-xs font-bold uppercase text-gray-500">Desde<input className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" type="date" disabled={preset!=='custom'} value={filters.fechaInicio} onChange={event=>setFilters({...filters,fechaInicio:event.target.value})}/></label><label className="text-xs font-bold uppercase text-gray-500">Hasta<input className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" type="date" disabled={preset!=='custom'} value={filters.fechaFin} onChange={event=>setFilters({...filters,fechaFin:event.target.value})}/></label><label className="text-xs font-bold uppercase text-gray-500">Categoría<select className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" value={filters.categoria} onChange={event=>setFilters({...filters,categoria:event.target.value})}><option value="">Todas</option>{categories.map(category=><option key={category}>{category}</option>)}</select></label><label className="text-xs font-bold uppercase text-gray-500">Producto<input list="analytics-products" className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" placeholder="Buscar por SKU" value={filters.sku} onChange={event=>setFilters({...filters,sku:event.target.value})}/><datalist id="analytics-products">{products.map(product=><option key={product.id} value={product.sku}>{product.nombre}</option>)}</datalist></label><button className="self-end rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white disabled:opacity-60" disabled={loading}>{loading?'Consultando...':'Aplicar filtros'}</button></div></form>
    {error&&<p className="mt-5 rounded-lg bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <div className="mt-6 grid gap-5 md:grid-cols-3"><article className="rounded-lg bg-white p-5 shadow-md"><p className="text-sm text-gray-500">Ventas acumuladas</p><p className="mt-2 text-3xl font-bold">{money(indicators.ventasAcumuladas)}</p></article><article className="rounded-lg bg-white p-5 shadow-md"><p className="text-sm text-gray-500">Transacciones</p><p className="mt-2 text-3xl font-bold">{indicators.transacciones||0}</p></article><article className="rounded-lg bg-white p-5 shadow-md"><p className="text-sm text-gray-500">Variación neta de inventario</p><p className={`mt-2 text-3xl font-bold ${Number(indicators.variacionNetaInventario)<0?'text-red-700':'text-emerald-700'}`}>{Number(indicators.variacionNetaInventario||0)>0?'+':''}{indicators.variacionNetaInventario||0}</p></article></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><article className="rounded-lg bg-white p-6 shadow-md"><h2 className="font-bold text-gray-900">Ventas acumuladas en el tiempo</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={report?.ventasEnElTiempo||[]}><defs><linearGradient id="analyticsSales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.3}/><stop offset="95%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="x" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={value=>money(value)}/><Area type="monotone" dataKey="y" name="Ventas" stroke="#2563eb" strokeWidth={2} fill="url(#analyticsSales)"/></AreaChart></ResponsiveContainer></div></article><article className="rounded-lg bg-white p-6 shadow-md"><h2 className="font-bold text-gray-900">Productos con mayor movimiento</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={report?.productosMayorMovimiento||[]} layout="vertical" margin={{left:24}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="sku" width={80} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="cantidad" name="Unidades vendidas" fill="#0f766e" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></article></div>
    <article className="mt-6 rounded-lg bg-white p-6 shadow-md"><h2 className="font-bold text-gray-900">Variación neta diaria del inventario</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={report?.variacionesInventario||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="x" tick={{fontSize:11}}/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="y" name="Variación neta" stroke="#dc2626" strokeWidth={2}/></LineChart></ResponsiveContainer></div></article>
  </section>
}
export default AnalyticsDashboardPage
