import { useEffect, useRef, useState } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useSession } from '../identity-access/application/session-store'
import { analyticsApi } from '../monitoring-analytics/application/analytics-api'

const baseItems=[['Dashboard','/dashboard'],['Catálogo','/catalogo'],['Inventario','/inventario'],['Terminal POS','/pos'],['Historial','/ventas'],['Usuarios','/usuarios'],['Configuración','/configuracion'],['Suscripción','/suscripcion']]

function Layout(){
  const navigate=useNavigate(); const{logout,plan}=useSession(); const[criticalAlert,setCriticalAlert]=useState(null); const lastAlertId=useRef(0); const since=useRef(null)
  const items=plan?.dashboardAnalitico?[['Dashboard','/dashboard'],['Analítica','/analitica'],...baseItems.slice(1)]:baseItems
  const exit=()=>{logout();navigate('/login')}
  useEffect(()=>{let active=true;since.current=new Date(Date.now()-5*60*1000).toISOString();const poll=async()=>{try{const response=await analyticsApi.stockZeroAlerts({afterId:lastAlertId.current,desde:since.current});const alerts=response.data||[];if(!active||!alerts.length)return;lastAlertId.current=Math.max(...alerts.map(alert=>Number(alert.id)));setCriticalAlert(alerts.at(-1))}catch{/* El estado de conexión general maneja errores persistentes. */}};poll();const timer=setInterval(poll,20000);return()=>{active=false;clearInterval(timer)}},[])
  useEffect(()=>{if(!criticalAlert)return undefined;const timer=setTimeout(()=>setCriticalAlert(null),9000);return()=>clearTimeout(timer)},[criticalAlert])
  return <div className="flex min-h-screen bg-gray-50"><aside className="sticky top-0 flex h-screen w-64 shrink-0 flex-col bg-slate-900 p-4 text-white"><div className="border-b border-slate-700 px-2 pb-5"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-300">SafeStock</p><h1 className="mt-2 text-xl font-bold">Analytics</h1><span className="mt-3 inline-block rounded-full bg-slate-800 px-3 py-1 text-xs text-blue-200">Plan {plan?.nombre||'...'}</span></div><nav className="mt-6 flex flex-1 flex-col gap-1">{items.map(([label,to])=><NavLink key={to} to={to} className={({isActive})=>`rounded-lg px-4 py-3 text-sm font-medium transition ${isActive?'bg-blue-600 text-white shadow-md':'text-slate-300 hover:bg-slate-800 hover:text-white'}`}>{label}</NavLink>)}</nav><button onClick={exit} className="rounded-lg border border-slate-700 px-4 py-3 text-left text-sm font-semibold text-slate-200 hover:bg-slate-800">Cerrar sesión</button></aside><div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-gray-100 bg-white px-8 shadow-sm"><div><p className="text-sm font-bold text-gray-900">SafeStock Analytics</p><p className="text-xs text-gray-500">Control operativo y antifraude</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Sistema conectado</span></header><main className="p-8"><Outlet/></main></div>{criticalAlert&&<div role="alert" aria-live="assertive" className="fixed right-6 top-20 z-50 w-full max-w-md rounded-lg border border-red-400 bg-red-700 p-5 text-white shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-red-100">Alerta crítica de inventario</p><p className="mt-2 text-sm font-semibold leading-6">{criticalAlert.message}</p><p className="mt-2 text-xs text-red-100">{new Date(criticalAlert.fecha_hora).toLocaleString('es-PE')}</p></div><button onClick={()=>setCriticalAlert(null)} aria-label="Cerrar alerta" className="rounded p-1 text-xl leading-none hover:bg-red-800">×</button></div></div>}</div>
}
export default Layout
